sync_time:
  description: Syncronize gateway's time to HA local time.

send_message:
  description: Send an arbitrary (but valid) OpenWebNet message to the gateway.
  fields:
    message:
      description: Valid OpenWebNet message.
      example: "*1*0*0##"

registry_cleanup:
  description: Cleanup the device and entity registries when an entity has been removed from the config file. (This service should be called after a restart of Home Assistant)

start_sending_instant_power:
  description: Get automatic instant power draw updates for a sensor.
  fields:
    entity_id:
      description: Name(s) of entities that will start sending instant power information.
      example: "sensor.general_power"
    duration:
      description: For how long the instant power information will be sent.
      example: "60"
